[tools]
node = "24.13.1"
pnpm = "11.10.0"
"npm:vite-plus" = "1.0.0"
gitleaks = "8.30.1"
hk = { version = "2.4.0", os = ["linux", "windows", "macos/arm64"] }
actionlint = "1.7.12"
shellcheck = "0.11.0"

[env]
HK_CONFIG_DIR = "{{config_root}}/.hk-config"

[tasks."hooks:install"]
run = "vp hooks disable && hk install --force-local --mise"
