apply plugin: 'com.android.library'
apply plugin: 'org.jetbrains.kotlin.android'

group = 'expo.modules.supacoderelaytunnel'
version = '0.0.0'

android {
  namespace 'expo.modules.supacoderelaytunnel'
  compileSdk rootProject.ext.compileSdkVersion
  defaultConfig {
    minSdkVersion rootProject.ext.minSdkVersion
    targetSdkVersion rootProject.ext.targetSdkVersion
  }
}

dependencies {
  implementation project(':expo-modules-core')
  implementation 'com.squareup.okhttp3:okhttp:4.12.0'
  implementation 'com.google.crypto.tink:tink-android:1.20.0'
}
